name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Match your Azure runtime

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Archive the app for deployment
      - name: Zip the application files
        run: |
          zip -r app.zip . -x "**/.git*" "**/__pycache__*" "**/tests*"

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "app"  # Replace with your Azure Web App name
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: app.zip
